export const amzGlobalRoyaltyAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: '_amzToken', internalType: 'address', type: 'address' },
      { name: '_vipModule', internalType: 'address', type: 'address' },
      { name: '_usdt', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'error', inputs: [], name: 'ReentrancyGuardReentrantCall' },
  {
    type: 'error',
    inputs: [{ name: 'token', internalType: 'address', type: 'address' }],
    name: 'SafeERC20FailedOperation',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'member',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'vipLevel',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'position',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'AddedToWaitlist',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'totalAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'timestamp',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'DailyDistributed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'vipLevel',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'membersCount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'LevelDistributed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'member',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'vipLevel',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'fromWaitlist',
        internalType: 'bool',
        type: 'bool',
        indexed: false,
      },
    ],
    name: 'MemberAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'member',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'vipLevel',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'reason',
        internalType: 'string',
        type: 'string',
        indexed: false,
      },
    ],
    name: 'MemberRemoved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'oldMember',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newMember',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'vipLevel',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
    ],
    name: 'MemberReplaced',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'timestamp',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'RoyaltyDeposited',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'member',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'fromLevel',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      { name: 'toLevel', internalType: 'uint8', type: 'uint8', indexed: false },
    ],
    name: 'VIPUpgraded',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DAY',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_CLAIM_DAYS',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_MEMBERS_PER_LEVEL',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_VIP_LEVEL',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MISSED_DAYS_THRESHOLD',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint8', type: 'uint8' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'activeMembers',
    outputs: [
      { name: 'memberAddress', internalType: 'address', type: 'address' },
      { name: 'joinedAt', internalType: 'uint64', type: 'uint64' },
      { name: 'lastClaimDate', internalType: 'uint64', type: 'uint64' },
      { name: 'claimDaysUsed', internalType: 'uint256', type: 'uint256' },
      { name: 'totalClaimed', internalType: 'uint256', type: 'uint256' },
      { name: 'isPermanent', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'amzToken',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'dailyRoyaltyPool',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'royaltyAmount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'depositRoyalty',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'distributeDailyRoyalty',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'level', internalType: 'uint8', type: 'uint8' }],
    name: 'getActiveMembers',
    outputs: [
      { name: 'addresses', internalType: 'address[]', type: 'address[]' },
      { name: 'claimDaysUsed', internalType: 'uint256[]', type: 'uint256[]' },
      { name: 'totalClaimed', internalType: 'uint256[]', type: 'uint256[]' },
      { name: 'lastClaimDates', internalType: 'uint64[]', type: 'uint64[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'level', internalType: 'uint8', type: 'uint8' }],
    name: 'getExpectedDailyEarning',
    outputs: [{ name: 'perMember', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'level', internalType: 'uint8', type: 'uint8' }],
    name: 'getLevelStats',
    outputs: [
      { name: 'activeMembersCount', internalType: 'uint256', type: 'uint256' },
      { name: 'waitlistCount', internalType: 'uint256', type: 'uint256' },
      { name: 'availableSpots', internalType: 'uint256', type: 'uint256' },
      {
        name: 'totalDistributedToday',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'member', internalType: 'address', type: 'address' }],
    name: 'getMemberDetails',
    outputs: [
      { name: 'isActive', internalType: 'bool', type: 'bool' },
      { name: 'activeLevel', internalType: 'uint8', type: 'uint8' },
      { name: 'claimDaysUsed', internalType: 'uint256', type: 'uint256' },
      { name: 'claimDaysRemaining', internalType: 'uint256', type: 'uint256' },
      { name: 'totalClaimed', internalType: 'uint256', type: 'uint256' },
      { name: 'lastClaimDate', internalType: 'uint64', type: 'uint64' },
      { name: 'isPermanent', internalType: 'bool', type: 'bool' },
      { name: 'waitlistPosition', internalType: 'uint256', type: 'uint256' },
      { name: 'activeMembersCount', internalType: 'uint256', type: 'uint256' },
      { name: 'canClaim', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getRoyaltyPoolStatus',
    outputs: [
      { name: 'totalPool', internalType: 'uint256', type: 'uint256' },
      { name: 'dailyPool', internalType: 'uint256', type: 'uint256' },
      { name: 'lastDistribution', internalType: 'uint256', type: 'uint256' },
      { name: 'canDistribute', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'level', internalType: 'uint8', type: 'uint8' }],
    name: 'getWaitlist',
    outputs: [
      { name: 'addresses', internalType: 'address[]', type: 'address[]' },
      { name: 'requestedAt', internalType: 'uint64[]', type: 'uint64[]' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint8', type: 'uint8' },
      { name: '', internalType: 'address', type: 'address' },
    ],
    name: 'inWaitlist',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'lastDistributionDate',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'lastDistributionTime',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'level', internalType: 'uint8', type: 'uint8' }],
    name: 'manualCleanup',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'memberActiveLevel',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'member', internalType: 'address', type: 'address' },
      { name: 'vipLevel', internalType: 'uint8', type: 'uint8' },
    ],
    name: 'registerVIPMember',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'royaltyPool',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'usdt',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'vipModule',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'vipPercentages',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: '', internalType: 'uint8', type: 'uint8' },
      { name: '', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'waitlist',
    outputs: [
      { name: 'memberAddress', internalType: 'address', type: 'address' },
      { name: 'requestedAt', internalType: 'uint64', type: 'uint64' },
    ],
    stateMutability: 'view',
  },
] 

export const amzTokenAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'usdtToken_', internalType: 'address', type: 'address' },
      { name: 'treasury_', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'error',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'allowance', internalType: 'uint256', type: 'uint256' },
      { name: 'needed', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'ERC20InsufficientAllowance',
  },
  {
    type: 'error',
    inputs: [
      { name: 'sender', internalType: 'address', type: 'address' },
      { name: 'balance', internalType: 'uint256', type: 'uint256' },
      { name: 'needed', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'ERC20InsufficientBalance',
  },
  {
    type: 'error',
    inputs: [{ name: 'approver', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidApprover',
  },
  {
    type: 'error',
    inputs: [{ name: 'receiver', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidReceiver',
  },
  {
    type: 'error',
    inputs: [{ name: 'sender', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidSender',
  },
  {
    type: 'error',
    inputs: [{ name: 'spender', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidSpender',
  },
  { type: 'error', inputs: [], name: 'ReentrancyGuardReentrantCall' },
  {
    type: 'error',
    inputs: [{ name: 'token', internalType: 'address', type: 'address' }],
    name: 'SafeERC20FailedOperation',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'phase', internalType: 'uint8', type: 'uint8', indexed: true },
      { name: 'periods', internalType: 'uint8', type: 'uint8', indexed: false },
      {
        name: 'grossTokens',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'feeTokens',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'netTokens',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Claim',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'phase', internalType: 'uint8', type: 'uint8', indexed: true },
      {
        name: 'depositUSDCents',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'usdtAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'baseUSDCentsAfter',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'referrer',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'firstDepositReferralPaid',
        internalType: 'bool',
        type: 'bool',
        indexed: false,
      },
    ],
    name: 'DepositMade',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'referrer',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'ReferrerSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'seller',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'usdtReceived',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Sold',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'referrer',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
    ],
    name: 'TeamLinked',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'level', internalType: 'uint8', type: 'uint8', indexed: false },
    ],
    name: 'VIPAchieved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'grossTokens',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'feeTokens',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'netTokens',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'VIPClaimed',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'upline',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'VIPUpgrade1Counted',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'grossTokens',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'feeTokens',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'netTokens',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'WithdrawClaimed',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DAY',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'DEEP_REF_WINDOW',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'EARLY_DEPOSIT_WINDOW',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_CYCLES_PER_PHASE',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_PAYOUTS',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_TOTAL_CLAIMS',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_UPLINE_DEPTH',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'referrer', internalType: 'address', type: 'address' },
      { name: 'child', internalType: 'address', type: 'address' },
    ],
    name: 'addDirectVip1',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
      { name: 'level', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'addRoyaltyHistory',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'claimAll',
    outputs: [{ name: 'totalNet', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'claimFeeBps',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'claimHistoryLength',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'claimReferral',
    outputs: [{ name: 'netOut', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'phase', internalType: 'uint8', type: 'uint8' },
    ],
    name: 'claimsBlocked',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'cents', internalType: 'uint256', type: 'uint256' },
      { name: 'periods', internalType: 'uint8', type: 'uint8' },
      { name: 'oneTime', internalType: 'bool', type: 'bool' },
    ],
    name: 'creditVipCents',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'depositUSDCents', internalType: 'uint256', type: 'uint256' },
      { name: 'ref', internalType: 'address', type: 'address' },
    ],
    name: 'deposit',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'depositHistoryLength',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'directRefPercent',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getClaimBlockers',
    outputs: [
      { name: 'blocked', internalType: 'bool', type: 'bool' },
      { name: 'blockingPhase', internalType: 'uint8', type: 'uint8' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'start', internalType: 'uint256', type: 'uint256' },
      { name: 'count', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getClaimHistory',
    outputs: [
      {
        name: 'out',
        internalType: 'struct AMZToken.ClaimHistory[]',
        type: 'tuple[]',
        components: [
          { name: 'claimAmount', internalType: 'uint256', type: 'uint256' },
          { name: 'netTokens', internalType: 'uint256', type: 'uint256' },
          { name: 'feeTokens', internalType: 'uint256', type: 'uint256' },
          { name: 'periods', internalType: 'uint256', type: 'uint256' },
          { name: 'tokenPrice', internalType: 'uint256', type: 'uint256' },
          { name: 'claimedAt', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getDeepReferralStatus',
    outputs: [
      { name: 'unlocked', internalType: 'bool', type: 'bool' },
      { name: 'directsInWindow', internalType: 'uint16', type: 'uint16' },
      { name: 'windowStart', internalType: 'uint64', type: 'uint64' },
      { name: 'windowEnd', internalType: 'uint64', type: 'uint64' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'start', internalType: 'uint256', type: 'uint256' },
      { name: 'count', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getDepositHistory',
    outputs: [
      {
        name: 'out',
        internalType: 'struct AMZToken.DepositHistory[]',
        type: 'tuple[]',
        components: [
          { name: 'depositAmount', internalType: 'uint256', type: 'uint256' },
          { name: 'tokenPrice', internalType: 'uint256', type: 'uint256' },
          { name: 'depositedAt', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'start', internalType: 'uint256', type: 'uint256' },
      { name: 'count', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getReferralClaimHistory',
    outputs: [
      {
        name: 'out',
        internalType: 'struct AMZToken.ReferralClaimHistory[]',
        type: 'tuple[]',
        components: [
          { name: 'claimAmount', internalType: 'uint256', type: 'uint256' },
          { name: 'tokenPrice', internalType: 'uint256', type: 'uint256' },
          { name: 'claimedAt', internalType: 'uint256', type: 'uint256' },
          { name: 'level', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getReferralInfo',
    outputs: [
      {
        name: 'availableReferralTokens',
        internalType: 'uint256',
        type: 'uint256',
      },
      {
        name: 'availableReferralUSDCents',
        internalType: 'uint256',
        type: 'uint256',
      },
      { name: 'lastReferralClaimAt', internalType: 'uint64', type: 'uint64' },
      { name: 'directReferrals', internalType: 'uint16', type: 'uint16' },
      { name: 'teamMembers', internalType: 'uint32', type: 'uint32' },
      { name: 'teamDepositsCents', internalType: 'uint256', type: 'uint256' },
      {
        name: 'teamReferralUSDCents',
        internalType: 'uint256',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'start', internalType: 'uint256', type: 'uint256' },
      { name: 'count', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getRoyaltyClaimHistory',
    outputs: [
      {
        name: 'out',
        internalType: 'struct AMZToken.RoyaltyClaimHistory[]',
        type: 'tuple[]',
        components: [
          { name: 'claimAmount', internalType: 'uint256', type: 'uint256' },
          { name: 'claimedAt', internalType: 'uint256', type: 'uint256' },
          { name: 'level', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'start', internalType: 'uint256', type: 'uint256' },
      { name: 'count', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getSellHistory',
    outputs: [
      {
        name: 'out',
        internalType: 'struct AMZToken.SellHistory[]',
        type: 'tuple[]',
        components: [
          { name: 'sellAmount', internalType: 'uint256', type: 'uint256' },
          { name: 'netTokens', internalType: 'uint256', type: 'uint256' },
          { name: 'feeTokens', internalType: 'uint256', type: 'uint256' },
          { name: 'tokenPrice', internalType: 'uint256', type: 'uint256' },
          { name: 'soldAt', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getUser',
    outputs: [
      { name: 'hasPlan', internalType: 'bool', type: 'bool' },
      { name: 'baseUSDCents', internalType: 'uint256', type: 'uint256' },
      { name: 'nextPhase', internalType: 'uint8', type: 'uint8' },
      {
        name: 'baseTranche',
        internalType: 'struct IAMZCore.TrancheView',
        type: 'tuple',
        components: [
          { name: 'amountUSDCents', internalType: 'uint256', type: 'uint256' },
          { name: 'active', internalType: 'bool', type: 'bool' },
          { name: 'needsReactivate', internalType: 'bool', type: 'bool' },
          { name: 'wasActiveBeforeGate', internalType: 'bool', type: 'bool' },
          { name: 'payoutsMade', internalType: 'uint8', type: 'uint8' },
          { name: 'claimCounts', internalType: 'uint8', type: 'uint8' },
          { name: 'availableCycles', internalType: 'uint8', type: 'uint8' },
          { name: 'currentCycle', internalType: 'uint64', type: 'uint64' },
          { name: 'nextClaimAt', internalType: 'uint64', type: 'uint64' },
        ],
      },
      {
        name: 'halfTranche',
        internalType: 'struct IAMZCore.TrancheView',
        type: 'tuple',
        components: [
          { name: 'amountUSDCents', internalType: 'uint256', type: 'uint256' },
          { name: 'active', internalType: 'bool', type: 'bool' },
          { name: 'needsReactivate', internalType: 'bool', type: 'bool' },
          { name: 'wasActiveBeforeGate', internalType: 'bool', type: 'bool' },
          { name: 'payoutsMade', internalType: 'uint8', type: 'uint8' },
          { name: 'claimCounts', internalType: 'uint8', type: 'uint8' },
          { name: 'availableCycles', internalType: 'uint8', type: 'uint8' },
          { name: 'currentCycle', internalType: 'uint64', type: 'uint64' },
          { name: 'nextClaimAt', internalType: 'uint64', type: 'uint64' },
        ],
      },
      {
        name: 'quarterTranche',
        internalType: 'struct IAMZCore.TrancheView',
        type: 'tuple',
        components: [
          { name: 'amountUSDCents', internalType: 'uint256', type: 'uint256' },
          { name: 'active', internalType: 'bool', type: 'bool' },
          { name: 'needsReactivate', internalType: 'bool', type: 'bool' },
          { name: 'wasActiveBeforeGate', internalType: 'bool', type: 'bool' },
          { name: 'payoutsMade', internalType: 'uint8', type: 'uint8' },
          { name: 'claimCounts', internalType: 'uint8', type: 'uint8' },
          { name: 'availableCycles', internalType: 'uint8', type: 'uint8' },
          { name: 'currentCycle', internalType: 'uint64', type: 'uint64' },
          { name: 'nextClaimAt', internalType: 'uint64', type: 'uint64' },
        ],
      },
      {
        name: 'totalDepositedUSDCents',
        internalType: 'uint256',
        type: 'uint256',
      },
      {
        name: 'totalRewardsUSDCents',
        internalType: 'uint256',
        type: 'uint256',
      },
      { name: 'referrer', internalType: 'address', type: 'address' },
      { name: 'nextClaimAt', internalType: 'uint256', type: 'uint256' },
      { name: 'lastDepositAt', internalType: 'uint256', type: 'uint256' },
      { name: 'depositAllowedAt', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'start', internalType: 'uint256', type: 'uint256' },
      { name: 'count', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getVIPClaimHistory',
    outputs: [
      {
        name: 'out',
        internalType: 'struct AMZToken.VIPClaimHistory[]',
        type: 'tuple[]',
        components: [
          { name: 'claimAmount', internalType: 'uint256', type: 'uint256' },
          { name: 'period', internalType: 'uint256', type: 'uint256' },
          { name: 'tokenPrice', internalType: 'uint256', type: 'uint256' },
          { name: 'claimedAt', internalType: 'uint256', type: 'uint256' },
          { name: 'oneTime', internalType: 'bool', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getVipEligibility',
    outputs: [
      { name: 'baseUSDCents', internalType: 'uint256', type: 'uint256' },
      { name: 'directs', internalType: 'uint16', type: 'uint16' },
      { name: 'directsVip1', internalType: 'uint16', type: 'uint16' },
      { name: 'teamTotal', internalType: 'uint32', type: 'uint32' },
      { name: 'lastDepositAt', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'fromTs', internalType: 'uint64', type: 'uint64' },
      { name: 'toTs', internalType: 'uint64', type: 'uint64' },
    ],
    name: 'getVipEligibilityRede',
    outputs: [
      { name: 'directs', internalType: 'uint16', type: 'uint16' },
      { name: 'dirVip1', internalType: 'uint16', type: 'uint16' },
      { name: 'team', internalType: 'uint32', type: 'uint32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'start', internalType: 'uint256', type: 'uint256' },
      { name: 'count', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'getWithdrawHistory',
    outputs: [
      {
        name: 'out',
        internalType: 'struct AMZToken.WithdrawHistory[]',
        type: 'tuple[]',
        components: [
          { name: 'claimAmount', internalType: 'uint256', type: 'uint256' },
          { name: 'netTokens', internalType: 'uint256', type: 'uint256' },
          { name: 'feeTokens', internalType: 'uint256', type: 'uint256' },
          { name: 'tokenPrice', internalType: 'uint256', type: 'uint256' },
          { name: 'claimedAt', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getWithdrawInfo',
    outputs: [
      { name: 'availableWithdraw', internalType: 'uint256', type: 'uint256' },
      {
        name: 'availableWithdrawTokens',
        internalType: 'uint256',
        type: 'uint256',
      },
      { name: 'totalWithdrawn', internalType: 'uint256', type: 'uint256' },
      {
        name: 'totalTokensWithdrawn',
        internalType: 'uint256',
        type: 'uint256',
      },
      { name: 'lastReferralClaimAt', internalType: 'uint64', type: 'uint64' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'cents', internalType: 'uint256', type: 'uint256' }],
    name: 'isAllowedPlan',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'l2RefPercent',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'l3RefPercent',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'maxPayout',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'pure',
  },
  {
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'phase', internalType: 'uint8', type: 'uint8' },
    ],
    name: 'nextClaimAtOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'pendingAllRewardsTokens',
    outputs: [
      { name: 'total', internalType: 'uint256', type: 'uint256' },
      { name: 'p0', internalType: 'uint256', type: 'uint256' },
      { name: 'p1', internalType: 'uint256', type: 'uint256' },
      { name: 'p2', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'phase', internalType: 'uint8', type: 'uint8' },
    ],
    name: 'pendingPhaseRewardTokens',
    outputs: [{ name: 'tokensDue', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'priceInCentsPerToken',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'refClaimFeeBps',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'referralClaimHistoryLength',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'referrerOf',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'rewardPeriod',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'royaltyClaimHistoryLength',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'royaltyModule',
    outputs: [
      { name: '', internalType: 'contract AMZGlobalRoyalty', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'tokenAmount', internalType: 'uint256', type: 'uint256' }],
    name: 'sell',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'sellAdminFeeBps',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'sellFeeBps',
    outputs: [{ name: '', internalType: 'uint16', type: 'uint16' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'sellHistoryLength',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'module', internalType: 'address', type: 'address' }],
    name: 'setRoyaltyModule',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'mod', internalType: 'address', type: 'address' }],
    name: 'setVipModule',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'treasury',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'usdt',
    outputs: [{ name: '', internalType: 'contract IERC20', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'usdtDecimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'vipClaimHistoryLength',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'vipModule',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'withdrawHistoryLength',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
] 

export const erc20Abi = [
  {
    type: 'error',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'allowance', internalType: 'uint256', type: 'uint256' },
      { name: 'needed', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'ERC20InsufficientAllowance',
  },
  {
    type: 'error',
    inputs: [
      { name: 'sender', internalType: 'address', type: 'address' },
      { name: 'balance', internalType: 'uint256', type: 'uint256' },
      { name: 'needed', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'ERC20InsufficientBalance',
  },
  {
    type: 'error',
    inputs: [{ name: 'approver', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidApprover',
  },
  {
    type: 'error',
    inputs: [{ name: 'receiver', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidReceiver',
  },
  {
    type: 'error',
    inputs: [{ name: 'sender', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidSender',
  },
  {
    type: 'error',
    inputs: [{ name: 'spender', internalType: 'address', type: 'address' }],
    name: 'ERC20InvalidSpender',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', internalType: 'string', type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
    stateMutability: 'nonpayable',
  },
] 

export const treasuryAbi = [
  {
    type: 'constructor',
    inputs: [
      { name: 'initialOwner', internalType: 'address', type: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  { type: 'error', inputs: [], name: 'BeneficiaryNotFound' },
  { type: 'error', inputs: [], name: 'InvalidPercentage' },
  { type: 'error', inputs: [], name: 'NoBalance' },
  {
    type: 'error',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'OwnableInvalidOwner',
  },
  {
    type: 'error',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'OwnableUnauthorizedAccount',
  },
  {
    type: 'error',
    inputs: [{ name: 'token', internalType: 'address', type: 'address' }],
    name: 'SafeERC20FailedOperation',
  },
  { type: 'error', inputs: [], name: 'TotalPercentageExceeds100' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'wallet',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'percentage',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'BeneficiaryAdded',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'wallet',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'BeneficiaryRemoved',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'wallet',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newPercentage',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'BeneficiaryUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'token',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'totalAmount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'TokensDistributed',
  },
  {
    type: 'function',
    inputs: [
      { name: 'wallet', internalType: 'address', type: 'address' },
      { name: 'percentage', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'addBeneficiary',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'beneficiaries',
    outputs: [
      { name: 'wallet', internalType: 'address', type: 'address' },
      { name: 'percentage', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'token', internalType: 'address', type: 'address' }],
    name: 'distribute',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'distributeNative',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getBeneficiaries',
    outputs: [
      {
        name: '',
        internalType: 'struct Treasury.Beneficiary[]',
        type: 'tuple[]',
        components: [
          { name: 'wallet', internalType: 'address', type: 'address' },
          { name: 'percentage', internalType: 'uint256', type: 'uint256' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getBeneficiaryCount',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'wallet', internalType: 'address', type: 'address' }],
    name: 'removeBeneficiary',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'newOwner', internalType: 'address', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  { type: 'receive', stateMutability: 'payable' },
] 

export const vipModuleAbi = [
  {
    type: 'constructor',
    inputs: [{ name: 'core_', internalType: 'address', type: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'isRede', internalType: 'bool', type: 'bool', indexed: false },
      { name: 'isOneTime', internalType: 'bool', type: 'bool', indexed: false },
      { name: 'level', internalType: 'uint8', type: 'uint8', indexed: false },
      {
        name: 'slotNumber',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'cents',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'ClaimCredit',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'level', internalType: 'uint8', type: 'uint8', indexed: false },
    ],
    name: 'CloseRedeWindow',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'level', internalType: 'uint8', type: 'uint8', indexed: false },
    ],
    name: 'CloseVipWindow',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'newLevel',
        internalType: 'uint8',
        type: 'uint8',
        indexed: false,
      },
      {
        name: 'timestamp',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
    ],
    name: 'LevelUp',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'level', internalType: 'uint8', type: 'uint8', indexed: false },
      {
        name: 'startAt',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
    ],
    name: 'OpenRedeWindow',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'level', internalType: 'uint8', type: 'uint8', indexed: false },
      {
        name: 'startAt',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
    ],
    name: 'OpenVipWindow',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'upline',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'redepositor',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      { name: 'isDirect', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'RedeCounted',
  },
  {
    type: 'function',
    inputs: [],
    name: 'MAX_UPLINE_DEPTH',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'claim',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'core',
    outputs: [{ name: '', internalType: 'contract IAMZCore', type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'currentTrack',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [],
    name: 'getAllLevelTables',
    outputs: [
      { name: 'selfCents', internalType: 'uint256[8]', type: 'uint256[8]' },
      { name: 'directsMin', internalType: 'uint16[8]', type: 'uint16[8]' },
      { name: 'directsVip1Min', internalType: 'uint16[8]', type: 'uint16[8]' },
      { name: 'teamMin', internalType: 'uint32[8]', type: 'uint32[8]' },
      { name: 'perClaimCents', internalType: 'uint256[8]', type: 'uint256[8]' },
      { name: 'oneTimeCents', internalType: 'uint256[8]', type: 'uint256[8]' },
      { name: 'redeAllowed', internalType: 'uint256[7]', type: 'uint256[7]' },
      { name: 'periodSeconds', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getClaimableCents',
    outputs: [
      { name: 'vipCents', internalType: 'uint256', type: 'uint256' },
      { name: 'redeCents', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'level', internalType: 'uint8', type: 'uint8' }],
    name: 'getLevelConfig',
    outputs: [
      { name: 'selfCents', internalType: 'uint256', type: 'uint256' },
      { name: 'directsMin', internalType: 'uint16', type: 'uint16' },
      { name: 'directsVip1Min', internalType: 'uint16', type: 'uint16' },
      { name: 'teamMin', internalType: 'uint32', type: 'uint32' },
      { name: 'perClaimCents', internalType: 'uint256', type: 'uint256' },
      { name: 'oneTimeCents', internalType: 'uint256', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getRedeProgress',
    outputs: [
      { name: 'level', internalType: 'uint8', type: 'uint8' },
      { name: 'claimsMade', internalType: 'uint8', type: 'uint8' },
      { name: 'nextAt', internalType: 'uint64', type: 'uint64' },
      { name: 'open', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getUserStateView',
    outputs: [
      {
        name: '',
        internalType: 'struct VIPModule.UserStateView',
        type: 'tuple',
        components: [
          { name: 'currentLevel', internalType: 'uint8', type: 'uint8' },
          { name: 'selfBaseCents', internalType: 'uint256', type: 'uint256' },
          { name: 'directsFirst', internalType: 'uint16', type: 'uint16' },
          { name: 'directsVip1', internalType: 'uint16', type: 'uint16' },
          { name: 'teamFirst', internalType: 'uint32', type: 'uint32' },
          { name: 'lastDepositAt', internalType: 'uint64', type: 'uint64' },
          {
            name: 'levelReachedAt',
            internalType: 'uint64[7]',
            type: 'uint64[7]',
          },
          { name: 'oneTimeClaimed', internalType: 'bool[7]', type: 'bool[7]' },
          {
            name: 'vip',
            internalType: 'struct VIPModule.WindowView',
            type: 'tuple',
            components: [
              { name: 'open', internalType: 'bool', type: 'bool' },
              { name: 'level', internalType: 'uint8', type: 'uint8' },
              { name: 'claimsMade', internalType: 'uint8', type: 'uint8' },
              { name: 'startAt', internalType: 'uint64', type: 'uint64' },
              { name: 'nextAt', internalType: 'uint64', type: 'uint64' },
              {
                name: 'redeDirectCount',
                internalType: 'uint16',
                type: 'uint16',
              },
              { name: 'redeTeamCount', internalType: 'uint32', type: 'uint32' },
            ],
          },
          {
            name: 'rede',
            internalType: 'struct VIPModule.WindowView',
            type: 'tuple',
            components: [
              { name: 'open', internalType: 'bool', type: 'bool' },
              { name: 'level', internalType: 'uint8', type: 'uint8' },
              { name: 'claimsMade', internalType: 'uint8', type: 'uint8' },
              { name: 'startAt', internalType: 'uint64', type: 'uint64' },
              { name: 'nextAt', internalType: 'uint64', type: 'uint64' },
              {
                name: 'redeDirectCount',
                internalType: 'uint16',
                type: 'uint16',
              },
              { name: 'redeTeamCount', internalType: 'uint32', type: 'uint32' },
            ],
          },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getVipEligibility',
    outputs: [
      { name: 'baseCents', internalType: 'uint256', type: 'uint256' },
      { name: 'directs', internalType: 'uint16', type: 'uint16' },
      { name: 'dirVip1', internalType: 'uint16', type: 'uint16' },
      { name: 'team', internalType: 'uint32', type: 'uint32' },
      { name: 'lastDepositAt', internalType: 'uint64', type: 'uint64' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: '', internalType: 'uint64', type: 'uint64' },
      { name: '', internalType: 'uint64', type: 'uint64' },
    ],
    name: 'getVipEligibilityRede',
    outputs: [
      { name: 'directs', internalType: 'uint16', type: 'uint16' },
      { name: 'dirVip1Zero', internalType: 'uint16', type: 'uint16' },
      { name: 'team', internalType: 'uint32', type: 'uint32' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'getVipProgress',
    outputs: [
      { name: 'level', internalType: 'uint8', type: 'uint8' },
      { name: 'claimsMade', internalType: 'uint8', type: 'uint8' },
      { name: 'nextAt', internalType: 'uint64', type: 'uint64' },
      { name: 'open', internalType: 'bool', type: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address', type: 'address' },
      { name: 'planCents', internalType: 'uint256', type: 'uint256' },
      { name: 'phase', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'onFirstDeposit',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [
      { name: 'redepositor', internalType: 'address', type: 'address' },
      { name: 'planCents', internalType: 'uint256', type: 'uint256' },
      { name: 'phase', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'onRedeDeposit',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'previewRedeLevel',
    outputs: [{ name: '', internalType: 'uint8', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'recomputeLevel',
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    inputs: [],
    name: 'royalty',
    outputs: [
      { name: '', internalType: 'contract AMZGlobalRoyalty', type: 'address' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    inputs: [{ name: 'module', internalType: 'address', type: 'address' }],
    name: 'setRoyaltyModule',
    outputs: [],
    stateMutability: 'nonpayable',
  },
] 

